<!--
    Copyright (c) 2026 Fujitsu Limited. All rights reserved.

    SPDX-License-Identifier: Apache-2.0
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.fujitsu.demo</groupId>
  <artifactId>chat06</artifactId>
  <packaging>jar</packaging>
  <version>1.0</version>
  <name>chat06</name>

  <properties>
    <java.version>25</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <lc4j.version>1.11.0</lc4j.version>
    <lc4j.cdi.version>1.0.0</lc4j.cdi.version>
    <otel.version>1.62.0</otel.version>
  </properties>
  
  <dependencies>

    <!-- Langchain4j -->
    <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j</artifactId>
      <version>${lc4j.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-google-ai-gemini</artifactId>
      <version>${lc4j.version}</version>
    </dependency>

    <!-- Langchain4j-CDI -->
    <dependency>
      <groupId>dev.langchain4j.cdi</groupId>
      <artifactId>langchain4j-cdi-core</artifactId>
      <version>${lc4j.cdi.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.langchain4j.cdi</groupId>
      <artifactId>langchain4j-cdi-portable-ext</artifactId>
      <version>${lc4j.cdi.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.langchain4j.cdi.mp</groupId>
      <artifactId>langchain4j-cdi-config</artifactId>
      <version>${lc4j.cdi.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.langchain4j.cdi.mp</groupId>
      <artifactId>langchain4j-cdi-telemetry</artifactId>
      <version>${lc4j.cdi.version}</version>
    </dependency>
	
    <!-- OpenTelmetry -->
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-sdk</artifactId>
      <version>${otel.version}</version>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-api</artifactId>
      <version>${otel.version}</version>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-sdk-metrics</artifactId>
      <version>${otel.version}</version>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-sdk-trace</artifactId>
      <version>${otel.version}</version>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-exporter-otlp</artifactId>
      <version>${otel.version}</version>
    </dependency>
    <dependency>
      <groupId>io.smallrye.opentelemetry</groupId>
      <artifactId>smallrye-opentelemetry-cdi</artifactId>
      <version>2.11.2</version>
    </dependency>
    <dependency>
      <groupId>io.smallrye.opentelemetry</groupId>
      <artifactId>smallrye-opentelemetry-config</artifactId>
      <version>2.11.2</version>
    </dependency>

    <!-- MicroProfile Config specification and implementation -->
    <dependency>
      <groupId>io.smallrye.config</groupId>
      <artifactId>smallrye-config</artifactId>
      <version>3.16.0</version>
    </dependency>
    <dependency>
      <groupId>org.eclipse.microprofile.config</groupId>
      <artifactId>microprofile-config-api</artifactId>
      <version>3.1</version>
    </dependency>

    <!-- CDI specification and implementation -->	
    <dependency>
      <groupId>org.jboss.weld.se</groupId>
      <artifactId>weld-se-core</artifactId>
      <version>6.0.4.Final</version>
    </dependency>
	<dependency>
      <groupId>jakarta.enterprise</groupId>
      <artifactId>jakarta.enterprise.cdi-api</artifactId>
      <version>4.1.0</version>
    </dependency>
  </dependencies>

  <build>
    <finalName>chat06</finalName>
    <plugins>
      <plugin>
	    <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.6.3</version>
        <configuration>
          <mainClass>com.fujitsu.demo.Chat06</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
