#
# Copyright (c) 2026 Fujitsu Limited. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

## parameters for OpenID Connect
oid.redirectUrl = ${OPENID_REDIRECT_URL}
oid.providerUrl = ${OPENID_PROVIDER_URL}
oid.clientId = ${OPENID_CLIENT_ID}
oid.clientSecret = ${OPENID_CLIENT_SECRET}

## URL of MCP server 
mcp.bank.url = http://localhost:9090/mcp

## api key for model
model.api.key = ${GOOGLE_API_KEY}

## model name
model.name = gemini-2.5-flash-lite

