#
# Copyright (c) 2026 Fujitsu Limited. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

## specify issuer of JWT
## i.e. mp.jwt.verify.issuer=https://accounts.google.com
mp.jwt.verify.issuer=XXXX

## specify the location of public key signed for JWT
## i.e. mp.jwt.verify.publickey.location=/META-INF/publickey-google.certs
mp.jwt.verify.publickey.location=XXXX

## principal name of JWT to be granted to access
## this is used in 'BankIdentityStore.java' .
bank.userid=${BANK_USERID}

