<!--
    Copyright (c) 2026 Fujitsu Limited. All rights reserved.

    SPDX-License-Identifier: Apache-2.0
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.fujitsu.demo</groupId>
  <artifactId>supervisor</artifactId>
  <packaging>war</packaging>
  <version>1.0</version>
  <name>supervisor</name>

  <properties>
    <java.version>25</java.version>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <lc4j.version>1.13.0</lc4j.version>
    <lc4j.mcp.version>1.13.0-beta23</lc4j.mcp.version>
  </properties>


  <dependencies>
    <!-- Jakarta API -->
    <dependency>
      <groupId>jakarta.platform</groupId>
      <artifactId>jakarta.jakartaee-api</artifactId>
      <version>11.0.0</version>
      <scope>provided</scope>
    </dependency>

    <!-- MicroProfile API -->
    <dependency>
      <groupId>org.eclipse.microprofile.config</groupId>
      <artifactId>microprofile-config-api</artifactId>
      <version>3.1</version>
      <scope>provided</scope>
    </dependency>

    <!-- Langchain4j -->
    <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j</artifactId>
      <version>${lc4j.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-agentic</artifactId>
      <version>${lc4j.mcp.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-mcp</artifactId>
      <version>${lc4j.mcp.version}</version>
    </dependency>
    <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-google-ai-gemini</artifactId>
      <version>${lc4j.version}</version>
    </dependency>

	
    <!-- Logging -->
    <dependency>
      <groupId>org.tinylog</groupId>
      <artifactId>tinylog-impl</artifactId>
      <version>2.6.2</version>
    </dependency>
    <dependency>
      <groupId>org.tinylog</groupId>
      <artifactId>slf4j-tinylog</artifactId>
      <version>2.6.2</version>
    </dependency>
	
  </dependencies>

  <build>
    <finalName>supervisor</finalName>
    <plugins>
      <plugin>
	<groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.5.1</version>
        <configuration>
          <failOnMissingWebXml>false</failOnMissingWebXml>
        </configuration>	
      </plugin>
    </plugins>
  </build>
</project>
